name: umt_timetable_parser
description: A sample command-line application.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.1.0
  html: ^0.15.4
  cookie_jar: ^4.0.8
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.4.3
